export const CONTENT_ID = 'content'
export const SIG_IN_DISCLAIMER_ID = 'sig-in-disclaimer'
export const SIGN_BUTTON_ID = 'sigh-button'
export const ADDITIONAL_SIGN_ANCHOR_ID = 'additional-sign-anchor'
export const ACCOUNT_INFO_CONTAINER_ID = 'account-info-container'
export const MARKET_TEMPLATE_ID = 'market'
export const ORDER_BOOK_ROW_ID = 'order-book-row'

export const SIG_IN_DISCLAIMER_SELECTOR = '.sig-in-disclaimer'
export const HEADER_ACCOUNT_NAME_SELECTOR = '.header__account-name'
export const HEADER_ACCOUNT_BALANCE_SELECTOR = '.header__account-balance'
export const MARKET_SELECTOR = '.market'
export const PAIRS_SELECT_SELECTOR = '.pairs-select'
export const ORDER_BOOK_SELECTOR = '.order-book'
export const SELL_CONTAINER_SELECTOR = '.order-book__sell-container'
export const SPREAD_SELECTOR = '.order-book__spread'
export const BUY_CONTAINER_SELECTOR = '.order-book__buy-container'
export const ORDER_BOOK_ROW_SELECTOR = '.order-book__row'
export const ORDER_BOOK_TITLE_ROW_SELECTOR = '.order-book__title-row'

export const HEADER_ACCOUNT_INFO_CONTAINER_HIDE_CLASS = 'header__account-info-container_hide'

export const SIGN_OUT_BUTTON_TEXT = 'Sign out'
export const SIGN_IN_BUTTON_TEXT = 'Sign in'
